#!/usr/bin/env bash
# Code generated by cmd/gen-language-artifacts; DO NOT EDIT.

codesieve_language_names=(go python rust php typescript javascript java csharp hcl json bash yaml)

codesieve_treesitter_languages=(python rust php typescript javascript java csharp hcl json bash yaml)

codesieve_is_known_treesitter_language() {
  local x="$1"
  local l
  for l in "${codesieve_treesitter_languages[@]}"; do
    if [ "$x" = "$l" ]; then
      return 0
    fi
  done
  return 1
}

codesieve_grammar_repo_for_language() {
  case "$1" in
    python) echo "https://github.com/tree-sitter/tree-sitter-python.git" ;;
    rust) echo "https://github.com/tree-sitter/tree-sitter-rust.git" ;;
    php) echo "https://github.com/tree-sitter/tree-sitter-php.git" ;;
    typescript) echo "https://github.com/tree-sitter/tree-sitter-typescript.git" ;;
    javascript) echo "https://github.com/tree-sitter/tree-sitter-javascript.git" ;;
    java) echo "https://github.com/tree-sitter/tree-sitter-java.git" ;;
    csharp) echo "https://github.com/tree-sitter/tree-sitter-c-sharp.git" ;;
    hcl) echo "https://github.com/tree-sitter-grammars/tree-sitter-hcl.git" ;;
    json) echo "https://github.com/tree-sitter/tree-sitter-json.git" ;;
    bash) echo "https://github.com/tree-sitter/tree-sitter-bash.git" ;;
    yaml) echo "https://github.com/tree-sitter/tree-sitter-yaml.git" ;;
    *) return 1 ;;
  esac
}

codesieve_grammar_dir_for_language() {
  case "$1" in
    python) echo "third_party/tree-sitter-python" ;;
    rust) echo "third_party/tree-sitter-rust" ;;
    php) echo "third_party/tree-sitter-php" ;;
    typescript) echo "third_party/tree-sitter-typescript" ;;
    javascript) echo "third_party/tree-sitter-javascript" ;;
    java) echo "third_party/tree-sitter-java" ;;
    csharp) echo "third_party/tree-sitter-csharp" ;;
    hcl) echo "third_party/tree-sitter-hcl" ;;
    json) echo "third_party/tree-sitter-json" ;;
    bash) echo "third_party/tree-sitter-bash" ;;
    yaml) echo "third_party/tree-sitter-yaml" ;;
    *) return 1 ;;
  esac
}
