package languages

import (
	"fmt"
	"slices"
	"strings"
)

func RenderSupportedLanguagesMarkdown() string {
	var b strings.Builder
	b.WriteString("# Supported languages\n\n")
	b.WriteString("<!-- Code generated by cmd/gen-language-artifacts; DO NOT EDIT. -->\n\n")
	b.WriteString("This is the canonical supported language matrix for `codesieve`.\n")
	b.WriteString("Other docs should link here instead of duplicating language lists.\n\n")
	b.WriteString("| Name | Parser | Extensions | Extra detection |\n")
	b.WriteString("| --- | --- | --- | --- |\n")
	for _, item := range All() {
		extra := ""
		if len(item.SupportsGlobs) > 0 {
			extra = strings.Join(item.SupportsGlobs, ", ")
		}
		if item.Notes != "" {
			if extra != "" {
				extra += "; "
			}
			extra += item.Notes
		}
		b.WriteString(fmt.Sprintf("| %s (`%s`) | %s | `%s` | %s |\n",
			item.DisplayName,
			item.Name,
			item.Parser,
			strings.Join(item.Extensions, "`, `"),
			blankDash(extra),
		))
	}
	b.WriteString("\n")
	b.WriteString("Tree-sitter grammar sources are vendored for reproducible Nix builds.\n")
	b.WriteString("See `docs/PARSERS.md` for layout and update workflow.\n")
	return b.String()
}

func RenderLanguageMapShell() string {
	var b strings.Builder
	b.WriteString("#!/usr/bin/env bash\n")
	b.WriteString("# Code generated by cmd/gen-language-artifacts; DO NOT EDIT.\n\n")
	b.WriteString("codesieve_language_names=(")
	all := All()
	for i, item := range all {
		if i > 0 {
			b.WriteString(" ")
		}
		b.WriteString(item.Name)
	}
	b.WriteString(")\n\n")

	ts := TreeSitter()
	b.WriteString("codesieve_treesitter_languages=(")
	for i, item := range ts {
		if i > 0 {
			b.WriteString(" ")
		}
		b.WriteString(item.Name)
	}
	b.WriteString(")\n\n")

	b.WriteString("codesieve_is_known_treesitter_language() {\n")
	b.WriteString("  local x=\"$1\"\n")
	b.WriteString("  local l\n")
	b.WriteString("  for l in \"${codesieve_treesitter_languages[@]}\"; do\n")
	b.WriteString("    if [ \"$x\" = \"$l\" ]; then\n")
	b.WriteString("      return 0\n")
	b.WriteString("    fi\n")
	b.WriteString("  done\n")
	b.WriteString("  return 1\n")
	b.WriteString("}\n\n")

	b.WriteString("codesieve_grammar_repo_for_language() {\n")
	b.WriteString("  case \"$1\" in\n")
	for _, item := range ts {
		b.WriteString(fmt.Sprintf("    %s) echo \"%s\" ;;\n", item.Name, item.GrammarRepo))
	}
	b.WriteString("    *) return 1 ;;\n")
	b.WriteString("  esac\n")
	b.WriteString("}\n\n")

	b.WriteString("codesieve_grammar_dir_for_language() {\n")
	b.WriteString("  case \"$1\" in\n")
	for _, item := range ts {
		b.WriteString(fmt.Sprintf("    %s) echo \"%s\" ;;\n", item.Name, item.GrammarDir))
	}
	b.WriteString("    *) return 1 ;;\n")
	b.WriteString("  esac\n")
	b.WriteString("}\n")

	return b.String()
}

func RenderParserBuiltinNames() []string {
	items := All()
	names := make([]string, 0, len(items))
	for _, item := range items {
		names = append(names, item.Name)
	}
	slices.Sort(names)
	return names
}

func RenderSupportedLanguagesSummary() string {
	items := All()
	names := make([]string, 0, len(items))
	for _, item := range items {
		names = append(names, item.Name)
	}
	return strings.Join(names, ", ")
}

func blankDash(s string) string {
	if strings.TrimSpace(s) == "" {
		return "-"
	}
	return s
}
